<Project>
    <PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
        <AvaloniaVersion>12.0.3</AvaloniaVersion>
    </PropertyGroup>
    <ItemGroup>
        <None Remove=".gitignore" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)'=='Debug'">
        <ProjectReference Include="$(SolutionDir)..\..\src\NP.Ava.Visuals.csproj" />
		<PackageReference Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.1" />
    </ItemGroup>
    <ItemGroup Condition="'$(Configuration)'=='Release'">
        <PackageReference Include="NP.Ava.Visuals" Version="1.0.55"/>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Avalonia.Desktop"
				  Version="$(AvaloniaVersion)" />
		<PackageReference Include="Avalonia.Themes.Simple"
						  Version="$(AvaloniaVersion)" />
	</ItemGroup>
</Project>
